### ISSUE TITLE
java.lang.IllegalArgumentException: n <= 0: 0

### ISSUE THREAD

**Issue by chenyunecjtu** [kaisengao/KsgLikeView#2]
java.lang.IllegalArgumentException: n <= 0: 0
    at java.util.Random.nextInt(Random.java:182)
    at com.kaisengao.likeview.like.KsgPathAnimator.getTogglePoint(KsgPathAnimator.java:145)
    at com.kaisengao.likeview.like.KsgPathAnimator.start(KsgPathAnimator.java:84)
    at com.kaisengao.likeview.like.KsgLikeView.addFavor(KsgLikeView.java:123)

**Comment by kaisengao** [comment]
这个问题应该是没有添加资源文件。
我更新了一下版本库，如果可以的话可以更新一下。
